// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycgflhujvwfszctkjzjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljZ2ZsaHVqdndmc3pjdGtqemprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDkyMjQsImV4cCI6MjA3MjU4NTIyNH0.-h3I-t6XxJveoHbc2UFZWkuPo-h5feewFtY150X4qdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});